---
language: ruby
bundler_args: --without development --jobs=3 --retry=3

sudo: false

rvm:
# Almost deprecated
#  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1

env:
# Almost deprecated
#  - PUPPET_VERSION="~> 2.7.0"
#  - PUPPET_VERSION="~> 3.1.0"
#  - PUPPET_VERSION="~> 3.2.0"
#  - PUPPET_VERSION="~> 3.3.0"
#  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"

before_install: rm Gemfile.lock || true
install: bundle install
script:
 - 'bundle exec rake validate'
 - 'bundle exec rake lint'
 - 'bundle exec rake syntax'
 - 'bundle exec rake template'
 - 'bundle exec rake spec'

matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.4.0"
