#!/bin/bash 
set -e

pushd $(dirname $0)
. $(basename $0).cfg

_echo() {
	echo "$(date +%Y%m%d-%H%M%S) - $1" | tee -a ${LogFile}
}

_echo "Server naming..."
echo "${ServerName}" > /etc/hostname
echo -e "127.0.0.1\tlocalhost" > /etc/hosts
echo -e "127.0.1.1\t${ServerName}" >> /etc/hosts

_echo "Enable the Puppet Labs Package Repository..."
wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
dpkg -i puppetlabs-release-precise.deb
rm puppetlabs-release-precise.deb
apt-get update

apt-get --yes autoremove 
apt-get --yes install puppetmaster puppet
apt-get --yes --fix-broken install

_echo "User ${DftUser} control..."
if [ X"${DftUser}" == X"$(awk -F":" -v var=${DftUser} '{ if ($1 == var) print $1; }' /etc/passwd)" ] ; then
	echo "User ${DftUser} is declared and will be the owner of this installation."
else
	echo "User ${DftUser} is not declared: Something went wrong."
	exit 1
fi

_echo "Sourcing the directories of the configuration..."
grep "dir=" ${confdir}/puppet.conf | while read Line
do
	eval chown -R ${DftUser}:${DftUser} $(echo ${Line} | awk -F"=" '{print $2}')
done

_echo "Puppet $(puppet --version) is installed on server $(hostname)."

_echo "Adding some modules..."
grep -v '^#' modules.lst |
while read Module
do
	_echo "puppet module install ${Module}"
	puppet module install ${Module}
done

for Thingy in modules manifests
do
	_echo "Importing ${Name} ${Thingy}..."
	cp -R ./${Thingy}/* ${confdir}/${Thingy}/           | tee -a ${LogFile}
	chown -R ${DftUser}:${DftUser} ${confdir}/${Thingy} | tee -a ${LogFIle}
done

popd
