alias ll="ls -l"
alias ls="ls --color=auto"
alias lof='sudo lsof -nP -p'
alias log="cd /var/log; ls"
alias mm="echo 'Hello dummy! I think you want to do ll, I know you...' ; ll"
alias sc="cd ~/scripts"
alias si="sudo vi"
alias smod="sudo chmod"
alias sown="sudo chown"
